using BoutiqueInventoryAPI.Data; using BoutiqueInventoryAPI.DTOs; using Microsoft.Data.SqlClient; using Microsoft.EntityFrameworkCore; using System.Data;
namespace BoutiqueInventoryAPI.Services;
public class StoredProcedureService:IStoredProcedureService{private readonly BoutiqueDbContext _context; public StoredProcedureService(BoutiqueDbContext context){_context=context;}
public async Task<int> InsertWarehouseAsync(WarehouseCreateDto dto){var newId=new SqlParameter("@NewId",SqlDbType.Int){Direction=ParameterDirection.Output}; await _context.Database.ExecuteSqlRawAsync("EXEC dbo.sp_InsertWarehouse @Name, @Location, @NewId OUTPUT",new SqlParameter("@Name",dto.Name),new SqlParameter("@Location",dto.Location),newId); return (int)newId.Value;}
public async Task UpdateWarehouseAsync(int id,WarehouseUpdateDto dto){await _context.Database.ExecuteSqlRawAsync("EXEC dbo.sp_UpdateWarehouse @Id, @Name, @Location, @IsActive",new SqlParameter("@Id",id),new SqlParameter("@Name",dto.Name),new SqlParameter("@Location",dto.Location),new SqlParameter("@IsActive",dto.IsActive));}
public async Task<int> InsertCategoryAsync(CategoryCreateDto dto){var newId=new SqlParameter("@NewId",SqlDbType.Int){Direction=ParameterDirection.Output}; await _context.Database.ExecuteSqlRawAsync("EXEC dbo.sp_InsertCategory @Name, @NewId OUTPUT",new SqlParameter("@Name",dto.Name),newId); return (int)newId.Value;}
public async Task UpdateCategoryAsync(int id,CategoryUpdateDto dto){await _context.Database.ExecuteSqlRawAsync("EXEC dbo.sp_UpdateCategory @Id, @Name",new SqlParameter("@Id",id),new SqlParameter("@Name",dto.Name));}
public async Task<int> InsertProductAsync(ProductCreateDto dto){var newId=new SqlParameter("@NewId",SqlDbType.Int){Direction=ParameterDirection.Output}; var categoryIds=string.Join(",",dto.CategoryIds.Distinct()); await _context.Database.ExecuteSqlRawAsync("EXEC dbo.sp_InsertProduct @Name, @Type, @Size, @ExpirationDate, @ImagePath, @WarehouseId, @ShelfLocation, @CategoryIds, @NewId OUTPUT",new SqlParameter("@Name",dto.Name),new SqlParameter("@Type",dto.Type),new SqlParameter("@Size",(object?)dto.Size??DBNull.Value),new SqlParameter("@ExpirationDate",(object?)dto.ExpirationDate??DBNull.Value),new SqlParameter("@ImagePath",(object?)dto.ImagePath??DBNull.Value),new SqlParameter("@WarehouseId",dto.WarehouseId),new SqlParameter("@ShelfLocation",dto.ShelfLocation),new SqlParameter("@CategoryIds",categoryIds),newId); return (int)newId.Value;}
public async Task UpdateProductAsync(int id,ProductUpdateDto dto){var categoryIds=string.Join(",",dto.CategoryIds.Distinct()); await _context.Database.ExecuteSqlRawAsync("EXEC dbo.sp_UpdateProduct @Id, @Name, @Type, @Size, @ExpirationDate, @ImagePath, @WarehouseId, @ShelfLocation, @CategoryIds",new SqlParameter("@Id",id),new SqlParameter("@Name",dto.Name),new SqlParameter("@Type",dto.Type),new SqlParameter("@Size",(object?)dto.Size??DBNull.Value),new SqlParameter("@ExpirationDate",(object?)dto.ExpirationDate??DBNull.Value),new SqlParameter("@ImagePath",(object?)dto.ImagePath??DBNull.Value),new SqlParameter("@WarehouseId",dto.WarehouseId),new SqlParameter("@ShelfLocation",dto.ShelfLocation),new SqlParameter("@CategoryIds",categoryIds));}}
